name: ml_project
channels:
  - defaults
  - conda-forge
dependencies:
  - python == 3.8.10
  - pandas
  - isort
  - altair
  - altair_viewer
  - altair_saver
  - matplotlib
  - seaborn
  - numpy
  - scikit-learn
  - scipy
  - vega